version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/src
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # Sẽ thêm sau nếu cần chạy riêng, mặc định dùng npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
